### ISSUE TITLE
Services for Location management (Maps)

### ISSUE THREAD

**Issue by arsenykonohovwork** [inspectah-curvaceous/inspectah-curvaceous#31]
- [x] Examine available free (for play) solutions that have robust API for dev purposes (document it);
- [x] Investigate common functionality for selected services (document it using spreadsheet);
- [x] Examine available design patterns that needs to be involved for gathering available functionality in further feature implementation (document it);
- [x] Document selected approach for implementation;

[Location services (documentation)](https://github.com/inspectah-curvaceous/inspectah-curvaceous/blob/release/autumn-1.0/docs/Location%20services.md)

# Services for displaying location of an Account

## Looking around location services

Exploring the world of location services you can find a lot of companies and theirs' apps that can help you to find places, make routes and etc.
For our projects i chose the following services:

* [HERE maps](https://here.com)
* [Google maps](https://cloud.google.com/maps-platform/)
* [Yandex maps](https://tech.yandex.ru/maps/)
* [Mapquest](https://developer.mapquest.com/)
* [Mapbox](https://www.mapbox.com/)

All of them have powerful and robust API. Not all features are free but those that are will be enough for us.
Let's go through all of them.

### HERE maps

This servce provides ["Maps API for JavaScript"](https://developer.here.com/documentation/maps/topics/overview.html). Main features of this API are:

* Efficient map rendering
* HERE Maps map data
* Geocoding
* Routing
* Enterprise routing
* Places
* Custom map objects
* Mouse and touch interaction
* Pre-built UI controls
* Integrated HERE StreetLevel

Also the Maps API for JavaScript is organized into a number of modules. Developers can therefore use the API efficiently by selecting only the modules which their applications require.

### Google maps

[The Maps JavaScript API](https://developers.google.com/maps/documentation/javascript/tutorial) lets customize maps with developer's content and imagery for display on web pages and mobile devices. The Maps JavaScript API features four basic map types (roadmap, satellite, hybrid, and terrain) which a developer can modify using layers and styles, controls and events, and various services and libraries.

To use the Maps JavaScript API, you must get an API key which you can then add to your app or website. The API key is used to track API requests associated with your project for quota, usage, and billing.

### Yandex maps

[The Yandex.Maps API](https://tech.yandex.com/maps/mapsapi/) offers a range of services for using Yandex technologies and map data in projects. The API can be used for virtually anything: show directions to an office, or display data on the map for visual analytics.

If something changes in Yandex.Maps (for instance, a new company is added or a highway interchange opens), these updates are immediately available in the project.

The Yandex.Maps API includes 3 products:

* JavaScript API and HTTP Geocoder API
* Places HTTP API
* Static API

Each of the API products can be used free of charge or for a fee, depending on type of a project and how many requests per day are making.

[The Yandex.Maps JavaScript API](https://tech.yandex.com/maps/doc/jsapi/2.1/quick-start/index-docpage/) is a set of JavaScript components for publishing interactive maps on website pages.

### Mapquest

MapQuest powers thousands of businesses with location-enabled geospatial solutions. It's APIs and SDKs allow access to a variety of maps and to core functions critical to geospatial applications, such as geocoding, routing, spatial search, type ahead, traffic, and etc.

Mapquest provides [MapQuest.js](https://developer.mapquest.com/documentation/mapquest-js/v1.3/), [MapQuest-GL.js](https://developer.mapquest.com/documentation/mapquest-gl/v0.4/) and [PlaceSearch.js](https://developer.mapquest.com/documentation/place-search-js/v1.0/) web SDKs.

MapQuest.js is a JavaScript library for interactive maps, geocoding, directions, and traffic. Map   Quest.js is powered by the MapQuest APIs and integrates with Leaflet.js.

MapQuest-GL.js is a JavaScript library for interactive maps, geocoding, directions, and traffic. MapQuest-GL.js is powered by the MapQuest APIs.

PlaceSearch.js allows to search for an information on the map.

### Mapbox

Mapbox is the location data platform for mobile and web applications. It provides building blocks to add location features like maps, search and navigation into any experience you create.

The Mapbox web services APIs allow for programmatic access to Mapbox tools and services. These APIs allows to retrieve information about an account, upload and change resources, use core Mapbox tools, like geocoding and directions.

It has [maps service](https://www.mapbox.com/api-documentation/?language=JavaScript#maps), [geocoding service](https://www.mapbox.com/api-documentation/?language=JavaScript#geocoding) and [directions service](https://www.mapbox.com/api-documentation/?language=JavaScript#directions)

## Common functionality for services

| | HERE maps | Google maps | Yandex maps | Mapquest | Mapbox |
|-| -------------- | ----------- | ----------- | -------- | ------ |
| Geocoding | + | + | + | + | + |
| Routing | + | + | + | + | + |
| Traffic | + | + | + | + | + |
| Incidents | + | + | + | + | + |
| Places | + | + | + | + | + |
| Clustering | + | + | + | + | + |
| Scaling | + | + | + | + | + | + |

### Adapter Pattern

Reading about different design patterns in JavaScript i decided that the "Adapter Pattern" will be suitable for our project.
This is a structural pattern where the interface of one class is translated into another. This pattern lets classes work together that could not otherwise because of incompatible interfaces.
It is often used to create wrappers for new refactored APIs so that other existing old APIs can still work with them. This is usually done when new implementations or code refactoring (done for reasons like performance gains) result in a different public API while the other parts of the system are still using the old API and hence needs to be adapted to work together.
In our case we will have APIs from different location services. They all have some common functionaity and we will be able to switch between them and choose those that we want.
I noticed one simple but useful example. Let's look at it.

#### Example of the Adapter Pattern

Here we have an old API i.e. OldCalculator class:

```javascript
// old interface
class OldCalculator {
  constructor() {
    this.operations = function(term1, term2, operation) {
      switch (operation) {
        case 'add':
          return term1 + term2;
        case 'sub':
          return term1 - term2;
        default:
          return NaN;
      }
    };
  }
}
```

And a new API i.e. NewCalculator class:

```javascript
// new interface
class NewCalculator {
  constructor() {
    this.add = function(term1, term2) {
      return term1 + term2;
    };
    this.sub = function(term1, term2) {
      return term1 - term2;
    };
  }
}
```

The OldCalculator class provides an operationmethod for both addition and subtraction while the NewCalculator provides separate methods for addition and subtraction. The Adapter class CalcAdapter wraps the NewCalculator to add the operation method to the public facing API while using its own addition and subtraction implementation under the hood:

```javascript
// Adapter Class
class CalcAdapter {
  constructor() {
    const newCalc = new NewCalculator();

    this.operations = function(term1, term2, operation) {
      switch (operation) {
        case 'add':
          // using the new implementation under the hood
          return newCalc.add(term1, term2);
        case 'sub':
          return newCalc.sub(term1, term2);
        default:
          return NaN;
      }
    };
  }
}
```

How can we use this? Here it is:

```javascript
const oldCalc = new OldCalculator();
console.log(oldCalc.operations(10, 5, 'add')); // 15

const newCalc = new NewCalculator();
console.log(newCalc.add(10, 5)); // 15

const adaptedCalc = new CalcAdapter();
console.log(adaptedCalc.operations(10, 5, 'add')); // 15;
```

I think this example has something in common with location services' APIs. For example if one of the services doesn't work or has been stopped one service can be automatically switched to another.

### Iterator Pattern

It is a behavioural design pattern that provides a way to access the elements of an aggregate object sequentially without exposing its underlying representation.

Iterators have a special kind of behaviour where we step through an ordered set of values one at a time by calling next() until we reach the end. The introduction of Iterator and Generators in ES6 made the implementation of iterator pattern extremely straightforward.

#### Example of the Iterator Pattern

There is a generator function passing an array of data and return its elements iteratively using next and yield.

```javascript
function* iteratorUsingGenerator(collection) {
  var nextIndex = 0;

  while (nextIndex < collection.length) {
    yield collection[nextIndex++];
  }
}
```

A generator function is a special type of function that works as a factory for iterators and can explicitly maintain its own internal state and yield values iteratively. It can pause and resume its own execution cycle.

```javascript
// usage
const gen = iteratorUsingGenerator(['Hi', 'Hello', 'Bye']);

console.log(gen.next().value); // 'Hi'
console.log(gen.next().value); // 'Hello'
console.log(gen.next().value); // 'Bye'
```

In our case we can send to the iteratorUsingGenerator function collection of objects which will represent different location services and then we can choose which one to use.

## Approach to implementation

Thinking about location-based service as a part of a project it's better to create it as an independent module that can be simply inserted, deleted or modified and doesn't rely on other parts or modules of the project. So we should consider this service as a third party project that other projects can use.

There are can be some preferences for it. The first one is that depends on the region different maps can be set by default. But it will be possible to switch to any other map that user wants.

Another functionality that can be include is how to display the map. For example on the same page or not, fullscreen or not. Also some functions can be turned off by default and a user can choose which of them he need to turn on.

One more preference is to check whether a service for a specific map is available. If not the user will be asked to switch to those that are working now.

Services should ask if the user want to share his location on the map. This will allow to make a route from the current location to the destiny point, see the history of visited places and etc. If not that logs won't be saved.

**Comment by iScous** [comment]
@arsenykonohovwork can you tell me more about how the documentation of the last part ("Document selected approach for implementation") of this issue should be look like. what needs to be include in this documentation

**Comment by arsenykonohovwork** [comment]
> @arsenykonohovwork can you tell me more about how the documentation of the last part ("Document selected approach for implementation") of this issue should be look like. what needs to be include in this documentation

you have to use automated process for documentation.
Hint: this documentation should be created from code;
Please examine what the available solutions there, and choose most appropriate one;

**Comment by iScous** [comment]
@arsenykonohovwork did you mean me or Vlad? because this issue is for me

**Comment by arsenykonohovwork** [comment]
@iScous Could you add reference to docs in description for this issue?
