### ISSUE TITLE
Dropdown component (ESNext);

### ISSUE THREAD

**Issue by arsenykonohovwork** [inspectah-curvaceous/inspectah-curvaceous#40]
# ISSUE ACs:

- [x] 1. Create library core;
- [x] 2. Create Dropdown component in pure JS;
- [x] 3. Implement component structure that allows you to import separate component as well as all library (by stack) components;
- [x] 4. Make preview and Documentation for component using stack of tech (pure, vue, react, angular etc..) for this component;

## DROPDOWN ACs:
- [x] 1. Multi-select;
- [x] 2. Multi-display;
- [x] 3. Extended internal template for items (chosen and those are dropped);
- [x] 4. Documentation;
- [x] 5. Preview;

**Comment by VladislavGulik** [comment]
dropdown like input dropdown or combobox or selectbox?

**Comment by arsenykonohovwork** [comment]
> @arsenykonohovwork, please could you clarify, dropdown should look like input dropdown/combobox/selectbox?

things should looks exact like you ask.

**Comment by VladislavGulik** [comment]
@arsenykonohovwork could you explain please, what does it mean "Multi-display"?

**Comment by arsenykonohovwork** [comment]
> @arsenykonohovwork could you explain please, what does it mean "Multi-display"?

@VladislavGulik You have to display as many items from multi-select options as you can;
